black-desk/ocppi

CMakeLists.txt, debian/rules
- build: update debian/rules
- chore: update version to 0.1.3
=> version 0.1.3

.github/workflows/release.yaml, .gitignore, CMakeLists.txt, cmake/PFL.cmake, debian/changelog, libs/runtime/examples/parse-config/CMakeLists.txt, libs/runtime/misc/cmake/ocppi__runtime-config.cmake.in, misc/cmake/ocppi-config.cmake.in, tools/upgrade-pfl.sh
- build: not install examples of runtime
- chore: update .gitignore
- build(deps): update PFL.cmake
- chore: update version to 0.1.4
=> add cmake config

CMakeLists.txt, cmake/PFL.cmake, debian/changelog
- build: remove a message
- build(deps): update PFL.cmake
=> Disable install when used as submodule

CMakeLists.txt, cmake/PFL.cmake, debian/changelog
- build(deps): update PFL.cmake
- chore: update version to 0.1.6
=> release 0.1.6

cmake/GitSemver.cmake, tools/upgrade-gitsemver.sh
- chore: add tools/upgrade-gitsemver.sh
- build(deps): upgrade GitSemver.cmake
=> upgrade GitSemver

.github/workflows/prerelease.yaml
=> ci: rename job in prerelease

cmake/CPM.cmake
=> buid(deps): upgrade CPM.cmake

cmake/GitSemver.cmake, libs/cli/examples/using-crun/CMakeLists.txt
- build: correct libsystemd name
- build: upgrade GitSemver.cmake
=> fix some build issue

debian/control
=> chore: update debian/control

libs/runtime/include/ocppi/runtime/config/ConfigLoader.hpp
=> fix(runtime): add missing pragma once

CMakeLists.txt
=> chore: update version to 0.1.8

.github/workflows/checks.yaml
=> ci: use checks@master

.github/workflows/checks.yaml
=> ci: use ccache and github cache

CMakeLists.txt
=> chore: release 0.1.9

CMakeLists.txt
=> chore: remove catch2 as there is no test for now

CMakeLists.txt
=> chore: release 0.1.10

libs/runtime/include/ocppi/runtime/config/types/Config.hpp, libs/runtime/include/ocppi/runtime/config/types/Generators.hpp, tools/codegen/fix.patch
It should be string map of string.
=> fix: correct annotations type

examples/parse-config/CMakeLists.txt, examples/parse-config/src/main.cpp, examples/using-crun/CMakeLists.txt, examples/using-crun/src/main.cpp, include/ocppi/cli/CLI.hpp, include/ocppi/cli/runc/Runc.hpp, include/ocppi/cli/youki/Youki.hpp, include/ocppi/runtime/GlobalOption.hpp, include/ocppi/runtime/Runtime.hpp, include/ocppi/runtime/SpecRuntime.hpp, src/ocppi/cli/CommonCLI.cpp
=> refact: use logger in examples

cmake/GitSemver.cmake
=> chore: upgrade GitSemver.cmake

CMakeLists.txt, include/ocppi/cli/CommonCLI.hpp, include/ocppi/runtime/RunOption.hpp, include/ocppi/runtime/Runtime.hpp, src/ocppi/cli/CommonCLI.cpp, src/ocppi/cli/runc/Runc.cpp, src/ocppi/cli/youki/Youki.cpp, src/ocppi/runtime/RunOption.cpp
=> feat: add new command `run`

include/ocppi/runtime/GlobalOption.hpp, src/ocppi/cli/CommonCLI.cpp
=> feat: add global option --root

include/ocppi/runtime/ExecOption.hpp, src/ocppi/cli/CommonCLI.cpp
=> feat: add params to exec command

CMakeLists.txt, include/ocppi/cli/CLI.hpp, include/ocppi/cli/CommonCLI.hpp, include/ocppi/runtime/FeaturesOption.hpp, include/ocppi/runtime/SpecRuntime.hpp, src/ocppi/cli/CommonCLI.cpp, src/ocppi/runtime/FeaturesOption.cpp
=> feat: add `features` command

CMakeLists.txt
=> chore: release 0.2.0

cmake/PFL.cmake
=> fix: upgrade PFL to fix export name

CMakeLists.txt
=> chore: release 0.2.1

cmake/PFL.cmake
=> fix: upgrade PFL to fix cmake config file not found

api/schema/ocppi-types-schema.json, include/ocppi/types/ContainerListItem.hpp, tools/codegen/README.md, tools/codegen/fix.patch
=> chore: update comments of extra types

src/ocppi/cli/Process.cpp
=> build: detect external libfmt

CMakeLists.txt
=> chore: release 0.2.3

CMakeLists.txt, cmake/PFL.cmake, examples/parse-config/CMakeLists.txt, examples/using-crun/CMakeLists.txt, examples/with-logger/CMakeLists.txt
=> build: upgrade PFL.cmake to v0.3.0

CMakeLists.txt
=> chore: bump version to 0.3.0
